apiVersion: compute.openstack.org/v1alpha1
kind: ComputeOpenStack
metadata:
  name: example-computeopenstack
spec:
  # Add fields here
  roleName: worker-osp
  clusterName: ostest
  baseWorkerMachineSetName: ostest-worker-0
  k8sServiceIp: 172.30.0.1
  apiIntIp: 192.168.111.5
  workers: 1
  corePinning: "4-7"
