apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-osp-operator
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-osp-operator
  template:
    metadata:
      labels:
        name: worker-osp-operator
    spec:
      serviceAccountName: worker-osp-operator
      containers:
        - name: worker-osp-operator
          # Replace this with the built image name
          image: quay.io/ltomasbo/compute-operator:v0.0.1
          command:
          - worker-osp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "worker-osp-operator"
