kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: worker-osp-operator
subjects:
- kind: ServiceAccount
  name: worker-osp-operator
  namespace: openshift-machine-api
roleRef:
  kind: ClusterRole
  name: worker-osp-operator
  apiGroup: rbac.authorization.k8s.io