// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeOpenStack) DeepCopyInto(out *ComputeOpenStack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeOpenStack.
func (in *ComputeOpenStack) DeepCopy() *ComputeOpenStack {
	if in == nil {
		return nil
	}
	out := new(ComputeOpenStack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeOpenStack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeOpenStackList) DeepCopyInto(out *ComputeOpenStackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeOpenStack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeOpenStackList.
func (in *ComputeOpenStackList) DeepCopy() *ComputeOpenStackList {
	if in == nil {
		return nil
	}
	out := new(ComputeOpenStackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeOpenStackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeOpenStackSpec) DeepCopyInto(out *ComputeOpenStackSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeOpenStackSpec.
func (in *ComputeOpenStackSpec) DeepCopy() *ComputeOpenStackSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeOpenStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeOpenStackStatus) DeepCopyInto(out *ComputeOpenStackStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeOpenStackStatus.
func (in *ComputeOpenStackStatus) DeepCopy() *ComputeOpenStackStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeOpenStackStatus)
	in.DeepCopyInto(out)
	return out
}
