apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: {{ .WorkerOspRole }}
  name: 06-{{ .WorkerOspRole }}-selinuxoff
spec:
  config:
    ignition:
      version: 2.2.0
  kernelArguments:
    - selinux=0